### ISSUE TITLE
[T-Re(e)plant] requester-chest

### ISSUE THREAD

**Issue by hasezoey** [ReikaKalseki/Reika_FactorioMods_Issues#52]
"failed to load mods: Error while loading entity prototype "tree-planter" (logistic-container): A requester-type chest with zero request slots makes no sense"

**Comment by ReikaKalseki** [comment]
Are you using the right version? I fixed this some time ago.

**Comment by hasezoey** [comment]
Sorry - Then Factorio dont update it when i click on update...

**Comment by hasezoey** [comment]
Or when i look in the mod forum, there it stands last version "2 weeks ago" (ingame it says "1 week ago" ...) and i have noticed this issue ~1 week ago, (firstly wrote on mod "Discussion", sorry) and since then, i saw no update to it ...

**Comment by hasezoey** [comment]
Re-installed the mod, (after the update (Version 1.0.64)) and still the same error:
(last lines out the log)
```
   5.438 Error ModManager.cpp:1023: Error while running setup for entity prototype "tree-planter" (logistic-container): A requester-type chest with zero request slots makes no sense.
   5.532 Loaded shader file Y:/Steam/steamapps/common/Factorio/data/core/graphics/shaders/game.cso
   5.532 Loaded shader file Y:/Steam/steamapps/common/Factorio/data/core/graphics/shaders/zoom-to-world.cso
   5.532 Loaded shader file Y:/Steam/steamapps/common/Factorio/data/core/graphics/shaders/alpha-mask.cso
   5.533 Initial atlas bitmap size is 16384
   5.533 Created atlas bitmap 192x5 [none]
   5.534 Created atlas bitmap 132x24 [no-crop, trilinear-filtering, icon, light]
   5.558 Sprites loaded
   5.558 Convert atlas 132x24 to: trilinear-filtering 
   5.567 Custom inputs active: 3
   5.574 Factorio initialised
   5.575 Mods to disable:Failed to load mods: Error while running setup for entity prototype "tree-planter" (logistic-container): A requester-type chest with zero request slots makes no sense.

Mods to be disabled:
• TreePlant

```

**Comment by ReikaKalseki** [comment]
It launches fine for me, and I am using a planting machine without error, and it is functioning. Are you using 0.16?

**Comment by hasezoey** [comment]
i Use Factorio 0.16.15 ( and the T-Re(e)plant is for 0.16)

**Comment by ReikaKalseki** [comment]
Then it should work, as it does for me.
  
Open your mod zip and paste the tree planter's prototype data.
